# This file is automatically generated by `python3 elf_template.py /workfolder/unpacker/experiments/bin/hw/orig-hw/`
elf_template = {}
elf_template["powerpc"] = {
	"source":"powerpc-buildroot-2020.08.3-musl",
	"size":32,
	"sex":2,
	"ident":b'\x7fELF\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00',
	"type":2,
	"machine":20,
	"version":1,
	"flags":0,
}
elf_template["mips64"] = {
	"source":"mips64-buildroot-2020.08.3-musl",
	"size":64,
	"sex":2,
	"ident":b'\x7fELF\x02\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00',
	"type":2,
	"machine":8,
	"version":1,
	"flags":1610612743,
}
elf_template["mips"] = {
	"source":"mips-buildroot-2020.08.3-musl",
	"size":32,
	"sex":2,
	"ident":b'\x7fELF\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00',
	"type":2,
	"machine":8,
	"version":1,
	"flags":1879052295,
}
elf_template["riscv32"] = {
	"source":"riscv32-buildroot-2020.08.3-glibc",
	"size":32,
	"sex":1,
	"ident":b'\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00',
	"type":2,
	"machine":243,
	"version":1,
	"flags":4,
}
elf_template["powerpc64"] = {
	"source":"powerpc64-buildroot-2020.08.3-musl",
	"size":64,
	"sex":2,
	"ident":b'\x7fELF\x02\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00',
	"type":2,
	"machine":21,
	"version":1,
	"flags":2,
}
elf_template["mips64el"] = {
	"source":"mips64el-buildroot-2020.08.3-glibc",
	"size":64,
	"sex":1,
	"ident":b'\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00',
	"type":2,
	"machine":8,
	"version":1,
	"flags":1610612743,
}
elf_template["sparc64"] = {
	"source":"sparc64-buildroot-2020.08.3-glibc",
	"size":64,
	"sex":2,
	"ident":b'\x7fELF\x02\x02\x01\x03\x00\x00\x00\x00\x00\x00\x00\x00',
	"type":2,
	"machine":43,
	"version":1,
	"flags":514,
}
elf_template["x86_64"] = {
	"source":"x86_64-buildroot-2020.08.3-uclibc",
	"size":64,
	"sex":1,
	"ident":b'\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00',
	"type":2,
	"machine":62,
	"version":1,
	"flags":0,
}
elf_template["i686"] = {
	"source":"i686-buildroot-2020.08.3-musl",
	"size":32,
	"sex":1,
	"ident":b'\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00',
	"type":2,
	"machine":3,
	"version":1,
	"flags":0,
}
elf_template["mipsel"] = {
	"source":"mipsel-buildroot-2020.08.3-uclibc",
	"size":32,
	"sex":1,
	"ident":b'\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00',
	"type":2,
	"machine":8,
	"version":1,
	"flags":1879052295,
}
elf_template["sparc"] = {
	"source":"sparc-buildroot-2020.08.3-uclibc",
	"size":32,
	"sex":2,
	"ident":b'\x7fELF\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00',
	"type":2,
	"machine":2,
	"version":1,
	"flags":0,
}
elf_template["aarch64"] = {
	"source":"aarch64-buildroot-2020.08.3-uclibc",
	"size":64,
	"sex":1,
	"ident":b'\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00',
	"type":2,
	"machine":183,
	"version":1,
	"flags":0,
}
elf_template["arm"] = {
	"source":"arm-buildroot-2020.08.3-musl",
	"size":32,
	"sex":1,
	"ident":b'\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00',
	"type":2,
	"machine":40,
	"version":1,
	"flags":83886592,
}
elf_template["riscv64"] = {
	"source":"riscv64-buildroot-2020.08.3-glibc",
	"size":64,
	"sex":1,
	"ident":b'\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00',
	"type":2,
	"machine":243,
	"version":1,
	"flags":4,
}
