import sys
from elfpack import ELFPack
from elfesteem.elf import *
from elfesteem.elf_init import *
import os

if __name__ == "__main__":

    rootdir = sys.argv[1]
    files = os.listdir(rootdir)

    print("# This file is automatically generated by `python3 elf_template.py %s`"%(rootdir))
    print("elf_template = {}")
    elf_templates = {}

    for f in files:
        arch = f.split("-")[0]

        if arch in elf_templates.keys():
            continue

        elf_in = ELFPack(open(rootdir+"/"+f, 'rb').read())

        elf_params = {}
        elf_params["source"]    = "\""+f+"\""
        elf_params["size"]      = elf_in.size
        elf_params["sex"]       = elf_in.sex
        elf_params["ident"]     = elf_in.Ehdr.ident
        elf_params["type"]      = elf_in.Ehdr.type
        elf_params["machine"]   = elf_in.Ehdr.machine
        elf_params["version"]   = elf_in.Ehdr.version
        elf_params["flags"]     = elf_in.Ehdr.flags

        print("elf_template[\"%s\"] = {"%(arch))
        for k, v in elf_params.items():
            print('\t"{}":{},'.format(k, v))
        print("}")

        elf_templates[arch] = elf_params

